#!/usr/bin/env bash
#
# deploy_gh_pages.sh — Publish RISC-V ALE to GitHub Pages.
#
# Can be run:
#   - Locally:  `make gh-pages`  (stashes uncommitted changes, restores after)
#   - In CI:     via GitHub Actions on push to master (GH_PAGES_CI=1)
#
# This script:
#   1. (Local only) Stashes uncommitted changes so the working tree is clean.
#   2. Creates (or resets) an orphan `gh-pages` branch.
#   3. Removes files that should not be deployed (local/, scripts/, crates/,
#      .gitmodules).
#   4. De-submodules `extensions/` so GitHub Pages serves its contents.
#   5. Adds a `.nojekyll` file so GitHub Pages doesn't strip `_`-prefixed
#      folders/files (Jekyll processing is disabled).
#   6. Commits and force-pushes the `gh-pages` branch to `origin`.
#   7. (Local only) Returns to the original branch, restores the submodule,
#      and pops the stash.
#
# ---------------------------------------------------------------------------

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"

BRANCH="gh-pages"
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
STASHED=0
DESUBMODULED=0

# In CI mode, skip stash/restore — the runner starts clean
if [ "${GH_PAGES_CI:-0}" = "1" ]; then
    CI_MODE=1
else
    CI_MODE=0
fi

cleanup() {
    if [ "$CI_MODE" -eq 1 ]; then
        return
    fi

    # Ensure we're back on the original branch
    git checkout -f "$CURRENT_BRANCH" 2>/dev/null || true

    # Restore the submodule if we de-submoduled it
    if [ "$DESUBMODULED" -eq 1 ]; then
        rm -rf extensions/
        git submodule update --init 2>/dev/null || true
    fi

    # Restore stashed changes
    if [ "$STASHED" -eq 1 ]; then
        echo "==> Restoring stashed changes..."
        git stash pop || echo "WARNING: Could not pop stash. Run 'git stash pop' manually."
    fi
}
trap cleanup EXIT

# --- 1. Stash uncommitted changes (local only) -------------------------------
if [ "$CI_MODE" -eq 0 ]; then
    echo "==> Checking for uncommitted changes..."
    if ! git diff --quiet || ! git diff --cached --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
        echo "    Stashing uncommitted changes (including untracked files)"
        git stash push --include-untracked -m "gh-pages-deploy-stash"
        STASHED=1
    else
        echo "    Working tree is clean — nothing to stash."
    fi
fi

# --- 2. Create orphan gh-pages branch ---------------------------------------
echo "==> Creating orphan branch: $BRANCH"

# Delete existing gh-pages branch if it exists
git branch -D "$BRANCH" 2>/dev/null || true

# Create a fresh orphan branch (working tree files are preserved on disk)
git checkout --orphan "$BRANCH"

# Clear the index (keep working tree files on disk)
git rm -rf --cached . >/dev/null 2>&1 || true

# --- 3. Remove files that should not be deployed -----------------------------
rm -rf local/ scripts/ crates/ .gitmodules

# --- 4. De-submodule extensions/ ---------------------------------------------
# Remove the submodule's .git file so the extensions/ files become regular
# tracked files instead of a submodule gitlink.
rm -f extensions/.git
DESUBMODULED=1

# --- 5. Add .nojekyll --------------------------------------------------------
# This prevents GitHub Pages from running Jekyll, which would otherwise
# drop files/folders starting with underscores (e.g. in vendor libs).
touch .nojekyll

# --- 6. Commit and push ------------------------------------------------------
echo "==> Committing to $BRANCH"

# Ensure git has an author identity (CI runners don't have one by default)
GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME:-github-actions[bot]}"
GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL:-github-actions[bot]@users.noreply.github.com}"
GIT_COMMITTER_NAME="${GIT_COMMITTER_NAME:-$GIT_AUTHOR_NAME}"
GIT_COMMITTER_EMAIL="${GIT_COMMITTER_EMAIL:-$GIT_AUTHOR_EMAIL}"
export GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL

git add -A
git commit -m "Deploy to GitHub Pages

Generated by deploy_gh_pages.sh"

echo "==> Pushing $BRANCH to origin (force)"
if [ "$CI_MODE" -eq 1 ]; then
    # In CI, push using the GITHUB_TOKEN
    git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "$BRANCH"
else
    git push --force origin "$BRANCH"
fi

# --- 7. Return to original branch (local only; cleanup trap handles it) -----
if [ "$CI_MODE" -eq 0 ]; then
    echo "==> Returning to branch: $CURRENT_BRANCH"
fi

echo ""
echo "gh-pages branch succesfully pushed."
