#!/usr/bin/env bash
#
# deploy_gh_pages.sh — Publish RISC-V ALE to GitHub Pages WITHOUT GitHub Actions.
#
# This script:
#   1. Stashes any uncommitted changes so the working tree is clean.
#   2. Creates (or resets) an orphan `gh-pages` branch.
#   3. Removes files that should not be deployed (local/, scripts/, .gitmodules).
#   4. De-submodules `extensions/` so GitHub Pages serves its contents.
#   5. Adds a `.nojekyll` file so GitHub Pages doesn't strip `_`-prefixed
#      folders/files (Jekyll processing is disabled).
#   6. Commits and force-pushes the `gh-pages` branch to `origin`.
#   7. Returns to the original branch, restores the submodule, and pops the stash.
#
# ---------------------------------------------------------------------------

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"

BRANCH="gh-pages"
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
STASHED=0
DESUBMODULED=0

cleanup() {
    # Ensure we're back on the original branch
    git checkout -f "$CURRENT_BRANCH" 2>/dev/null || true

    # Restore the submodule if we de-submoduled it
    if [ "$DESUBMODULED" -eq 1 ]; then
        rm -rf extensions/
        git submodule update --init 2>/dev/null || true
    fi

    # Restore stashed changes
    if [ "$STASHED" -eq 1 ]; then
        echo "==> Restoring stashed changes..."
        git stash pop || echo "WARNING: Could not pop stash. Run 'git stash pop' manually."
    fi
}
trap cleanup EXIT

# --- 1. Stash uncommitted changes --------------------------------------------
echo "==> Checking for uncommitted changes..."
if ! git diff --quiet || ! git diff --cached --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
    echo "    Stashing uncommitted changes (including untracked files)"
    git stash push --include-untracked -m "gh-pages-deploy-stash"
    STASHED=1
else
    echo "    Working tree is clean — nothing to stash."
fi

# --- 2. Create orphan gh-pages branch ---------------------------------------
echo "==> Creating orphan branch: $BRANCH"

# Delete existing gh-pages branch if it exists
git branch -D "$BRANCH" 2>/dev/null || true

# Create a fresh orphan branch (working tree files are preserved on disk)
git checkout --orphan "$BRANCH"

# Clear the index (keep working tree files on disk)
git rm -rf --cached . >/dev/null 2>&1 || true

# --- 3. Remove files that should not be deployed -----------------------------
rm -rf local/ scripts/ .gitmodules

# --- 4. De-submodule extensions/ ---------------------------------------------
# Remove the submodule's .git file so the extensions/ files become regular
# tracked files instead of a submodule gitlink.
rm -f extensions/.git
DESUBMODULED=1

# --- 5. Add .nojekyll --------------------------------------------------------
# This prevents GitHub Pages from running Jekyll, which would otherwise
# drop files/folders starting with underscores (e.g. in vendor libs).
touch .nojekyll

# --- 6. Commit and push ------------------------------------------------------
echo "==> Committing to $BRANCH"

git add -A
git commit -m "Deploy to GitHub Pages

Generated by deploy_gh_pages.sh"

echo "==> Pushing $BRANCH to origin (force)"
git push --force origin "$BRANCH"

# --- 7. Return to original branch (cleanup trap handles restoration) ----------
echo "==> Returning to branch: $CURRENT_BRANCH"

echo ""
echo "gh-pages branch succesfully pushed."
