#!/usr/bin/env bash
#
# deploy_gh_pages.sh — Deploy RISC-V ALE to GitHub Pages (CI only).
#

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"

BRANCH="gh-pages"

echo "==> Creating orphan branch: $BRANCH"
git checkout --orphan "$BRANCH"
git rm -rf --cached . >/dev/null 2>&1 || true

# Remove non-deployable source directories & files
rm -rf local/ scripts/ crates/ .gitmodules

# De-submodule extensions/ so GitHub Pages serves its contents directly
rm -f extensions/.git

# Disable Jekyll processing on GitHub Pages
touch .nojekyll

# Force-add WASM artifacts (ignored by wasm-pack's generated .gitignore on main)
if [ -d "modules/pkg" ]; then
    rm -f modules/pkg/.gitignore
    git add -f modules/pkg
fi

echo "==> Committing and pushing to $BRANCH"
GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME:-github-actions[bot]}"
GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL:-github-actions[bot]@users.noreply.github.com}"
GIT_COMMITTER_NAME="${GIT_COMMITTER_NAME:-$GIT_AUTHOR_NAME}"
GIT_COMMITTER_EMAIL="${GIT_COMMITTER_EMAIL:-$GIT_AUTHOR_EMAIL}"
export GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL

git add -A
git commit -m "Deploy to GitHub Pages

Generated by deploy_gh_pages.sh"

git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "$BRANCH"

echo "gh-pages branch successfully pushed."
