#!/usr/bin/env python3
"""Copy the TypeScript declarations that `wasm-pack` generates into the tree.

`modules/pkg/` is ignored by git, so the declarations `wasm-pack` writes there
are not available to a checkout that has not built the WASM. `make build` calls
this script, and the copy under `modules/types/` is committed. The `typecheck`
CI job then needs no Rust toolchain, and `git diff --exit-code modules/types/`
after a build proves the copy is current.
"""

import pathlib
import sys

HEADER = """// Generated by make build. Do not edit.
//
// Source: modules/pkg/riscv_rs.d.ts, written by wasm-pack from crates/riscv-rs.
// Run `make build` to refresh it. CI fails when this file is out of date.

"""

SOURCE = pathlib.Path("modules/pkg/riscv_rs.d.ts")
TARGET = pathlib.Path("modules/types/riscv_rs.generated.d.ts")


def main() -> int:
    if not SOURCE.exists():
        print(f"{SOURCE} is missing; run `make build` first.", file=sys.stderr)
        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    contents = HEADER + SOURCE.read_text()

    if TARGET.exists() and TARGET.read_text() == contents:
        return 0

    TARGET.write_text(contents)
    print(f"Updated {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
