import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

/**
 * The precache list is generated by `scripts/update_cache.py` from an
 * allowlist. It used to come from a blocklist, which let 166 entries and
 * 227 MB — three Unity builds, every test file, the fixtures, the Makefile —
 * reach every visitor's disk. These assertions are the regression fence.
 */
function readPrecacheList() {
  const source = fs.readFileSync(path.join(REPO_ROOT, "service_worker.js"), "utf8");
  const match = source.match(/var urlsToCache = \[([\s\S]*?)\];/);
  expect(match, "service_worker.js must declare urlsToCache").not.toBeNull();
  return JSON.parse("[" + match[1].replace(/'/g, '"') + "]");
}

const FORBIDDEN = [
  { name: "test sources", re: /(^|\/)tests\// },
  { name: "the Makefile", re: /(^|\/)Makefile$/ },
  { name: "the npm lockfile", re: /package-lock\.json$/ },
  { name: "fixture archives", re: /\.zip$/ },
  { name: "device dependency bundles", re: /extensions\/devices\/dependencies\// },
  { name: "type declarations", re: /\.d\.ts$/ },
  { name: "the compiler WASM", re: /modules\/(clang|lld)\.wasm$/ },
  { name: "non-woff2 fonts", re: /\.(eot|ttf|woff|svg)$/ },
];

const MAX_PRECACHE_BYTES = 5 * 1024 * 1024;

describe("service worker precache list", () => {
  const urls = readPrecacheList();

  it("is not empty and starts at the app root", () => {
    expect(urls.length).toBeGreaterThan(1);
    expect(urls[0]).toBe("./");
  });

  for (const { name, re } of FORBIDDEN) {
    it(`does not precache ${name}`, () => {
      const offenders = urls.filter((u) => re.test(u));
      expect(offenders, `${name} must not be precached`).toEqual([]);
    });
  }

  it("has no duplicate entries", () => {
    expect(new Set(urls).size).toBe(urls.length);
  });

  it("names only files that exist in the tree", () => {
    // `modules/pkg/` is a build artifact. Skip it when the tree is unbuilt so
    // this suite still runs on a fresh clone.
    const missing = urls
      .filter((u) => u !== "./" && !u.startsWith("./modules/pkg/"))
      .filter((u) => !fs.existsSync(path.join(REPO_ROOT, u.slice(2))));
    expect(missing).toEqual([]);
  });

  it(`totals less than ${MAX_PRECACHE_BYTES / 1024 / 1024} MB`, () => {
    let total = 0;
    for (const url of urls) {
      if (url === "./") continue;
      const file = path.join(REPO_ROOT, url.slice(2));
      if (fs.existsSync(file)) total += fs.statSync(file).size;
    }
    expect(total).toBeGreaterThan(0);
    expect(total).toBeLessThan(MAX_PRECACHE_BYTES);
  });
});
